name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  TARGETS: HuyEngineApp

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.31.6'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake (Debug)
        if: matrix.configuration == 'Debug'
        run: cmake --preset otladka

      - name: Configure CMake (Release)
        if: matrix.configuration == 'Release'
        run: cmake --preset reliz

      - name: Build (Debug)
        if: matrix.configuration == 'Debug'
        run: cmake --build --preset otladka

      - name: Build (Release)
        if: matrix.configuration == 'Release'
        run: cmake --build --preset reliz

      - name: Archive Artifacts (Debug)
        if: matrix.configuration == 'Debug'
        run: Compress-Archive -Path cmake-build-debug/bin/* -DestinationPath artifacts-${{matrix.configuration}}.zip

      - name: Archive Artifacts (Release)
        if: matrix.configuration == 'Release'
        run: Compress-Archive -Path cmake-build-release/bin/* -DestinationPath artifacts-${{matrix.configuration}}.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HuyEngine-Windows-${{matrix.configuration}}
          path: artifacts-${{matrix.configuration}}.zip
          if-no-files-found: error
